name: Deploy to Lightsail

on:
  push:
    branches:
      - main  # Cambia esto si usas una rama diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Copy files via SCP
        run: scp -o StrictHostKeyChecking=no -r ./* bitnami@ip-172-26-2-174:/home/bitnami/htdocs

      - name: Deploy
        run: ssh -o StrictHostKeyChecking=no bitnami@ip-172-26-2-174 'cd /home/bitnami && ./deploy.sh'
